## Statistical Functions

NumPy offers a powerful suite of statistical functions that allow for efficient computation of basic statistics on arrays. These functions can be applied to entire arrays or along specific axes for multi-dimensional data.

- np.sum(): Computes the sum of array elements over a given axis.
- np.min() and np.max(): Find the minimum and maximum values in an array.
- np.mean(): Calculates the arithmetic mean along the specified axis.
- np.median(): Computes the median along the specified axis.
- np.var(): Computes the variance of an array.
- np.std(): Computes the standard deviation.
- np.corrcoef(): Returns the correlation matrix, which measures the correlation strengths between variables.

In [1]:
import numpy as np

In [2]:
arr=np.random.randint(30,100,10)

In [13]:
arr

array([47, 56, 62, 77, 84, 54, 57, 65, 74, 70])

In [14]:
np.sum(arr)

646

In [15]:
np.mean(arr)

64.6

In [16]:
np.median(arr)

63.5

In [17]:
np.var(arr)

120.84

In [18]:
np.std(arr)

10.992724866929036

In [19]:
arr

array([47, 56, 62, 77, 84, 54, 57, 65, 74, 70])

In [20]:
arr2=np.random.randint(30,100,10)

In [21]:
arr2

array([34, 61, 37, 69, 90, 63, 49, 32, 99, 94])

In [22]:
arr

array([47, 56, 62, 77, 84, 54, 57, 65, 74, 70])

In [23]:
np.corrcoef(arr,arr2)

array([[1.        , 0.68328389],
       [0.68328389, 1.        ]])

In [24]:
np.corrcoef(arr,arr2)[1,0]

0.6832838925946966

In [8]:
#np.sum(): Computes the sum of array elements over a given axis.
# Creating an array
arr = np.array([[1, 2], [3, 4],[5,6]])

# Sum of all elements
total_sum = np.sum(arr)
print("Total sum:", total_sum)

# Sum along the first axis (sum of each column)
column_sum = np.sum(arr, axis=0)
print("Sum along columns:", column_sum)

# Sum along the second axis (sum of each row)
row_sum = np.sum(arr, axis=1)
print("Sum along rows:", row_sum)

Total sum: 21
Sum along columns: [ 9 12]
Sum along rows: [ 3  7 11]


In [ ]:
# Minimum of all elements
min_val = np.min(arr)
print("Minimum value:", min_val)

# Maximum of all elements
max_val = np.max(arr)
print("Maximum value:", max_val)


Minimum value: 1
Maximum value: 4


In [ ]:
# Mean of all elements
mean_val = np.mean(arr)
print("Mean value:", mean_val)

# Median of all elements
median_val = np.median(arr)
print("Median value:", median_val)


Mean value: 2.5
Median value: 2.5


In [ ]:
# Variance of all elements
variance = np.var(arr)
print("Variance:", variance)

# Standard deviation of all elements
std_dev = np.std(arr)
print("Standard deviation:", std_dev)


Variance: 1.25
Standard deviation: 1.118033988749895


In [ ]:
# Creating two arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# Compute correlation matrix
corr_matrix = np.corrcoef(x, y)
print("Correlation matrix between x and y:\n", corr_matrix)


Correlation matrix between x and y:
 [[ 1. -1.]
 [-1.  1.]]
