## Numpy Array, Array Shape and Dimension
- **Shape**: The shape of an array is a tuple of integers giving the size of the array along each dimension. The .shape attribute of an array returns this tuple.
- **Dimension**: The dimension or rank of an array is the number of axes or directions in the array. The .ndim attribute provides this information.


In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4,5])

In [3]:
arr_2d=np.array([[3,2],
                [4,5],
                [6,7]])

In [4]:
arr_3d=np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                 
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]],
                 
                 [[19,20,21],
                  [22,23,24],
                  [25,26,27]]])
                 

- `.size` attribute of a NumPy array returns the total number of elements in the array
- `.itemsize` attribute in NumPy is used to get the size, in bytes, of each element in the array.
- `.nbytes`: Returns the total number of bytes consumed by the elements of the array.

In [5]:
print("1D Array:", arr_1d)
print("Size of 1D Array:", arr_1d.size)
print("Bytes per element in 1D Array:", arr_1d.itemsize)
print("Total bytes of 1D Array:", arr_1d.nbytes)
print()

print("2D Array:\n", arr_2d)
print("Size of 2D Array:", arr_2d.size)
print("Bytes per element in 2D Array:", arr_2d.itemsize)
print("Total bytes of 2D Array:", arr_2d.nbytes)
print()

print("3D Array:\n", arr_3d)
print("Size of 3D Array:", arr_3d.size)
print("Bytes per element in 3D Array:", arr_3d.itemsize)
print("Total bytes of 3D Array:", arr_3d.nbytes)


1D Array: [1 2 3 4 5]
Size of 1D Array: 5
Bytes per element in 1D Array: 4
Total bytes of 1D Array: 20

2D Array:
 [[3 2]
 [4 5]
 [6 7]]
Size of 2D Array: 6
Bytes per element in 2D Array: 4
Total bytes of 2D Array: 24

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Size of 3D Array: 27
Bytes per element in 3D Array: 4
Total bytes of 3D Array: 108


### Creating Arrays Using Functions
NumPy provides several functions to create arrays in a convenient way:

In [6]:
# Create an array of zeros

zeros = np.zeros((2, 3))
print("Array of zeros:\n", zeros)

print()

# Create an array of ones
ones = np.ones((3, 2))
print("Array of ones:\n", ones)

print()

# Create an array with a range of elements
range_array = np.arange(10)  # Similar to Python's range
print("Range array:", range_array)

print()

# Create an array with evenly spaced numbers over a specified interval
linspace_array = np.linspace(0, 10, 5)
print("Linspace array:", linspace_array)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Range array: [0 1 2 3 4 5 6 7 8 9]

Linspace array: [ 0.   2.5  5.   7.5 10. ]


In [7]:
# Create a diagonal matrix
diag_matrix = np.diag([1, 2, 3])
print("Diagonal matrix:\n", diag_matrix)

print()

# Create an array filled with a specified value
full_array = np.full((2, 3), 7)
print("Full array:\n", full_array)

print()

# Create an identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)


Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

Full array:
 [[7 7 7]
 [7 7 7]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### NumPy Data Types
NumPy supports a greater variety of numerical data types than Python does. This specificity helps in optimizing performance.


In [8]:
# Create arrays with specified data types
int_array = np.array([1, 2, 3])
float_array = np.array([1.0, 2.0, 3.0])
string_array = np.array(['1', 'an'])

print("Integer Array:", int_array)
print("Integer Array datatype:", int_array.dtype)

print()
print("Float Array:", float_array)
print("Float Array datatype:", float_array.dtype)

print()
print("String Array:", string_array)
print("String Array datatype:", string_array.dtype)

Integer Array: [1 2 3]
Integer Array datatype: int32

Float Array: [1. 2. 3.]
Float Array datatype: float64

String Array: ['1' 'an']
String Array datatype: <U2


In [9]:
arr_2d[:1,1:]

array([[2]])

In [16]:
arr_2d[1,:2]

array([4, 5])

In [19]:
arr_2d[1]

array([4, 5])

In [20]:
arr_3d[1,1,1:3]

array([14, 15])

In [21]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [22]:
arr_3d[2,:1,:2]

array([[19, 20]])

# Agenda
- Generating Random Numbers
- How to manipulate and acess the array(indexing, slicing)
- Updating array

In [ ]:
import numpy as np

 ### Generating Random Numbers
 NumPy provides several functions in its random module to generate random numbers from different statistical distributions. Here's an overview of some common functions for generating random numbers:



1. `np.random.rand`\
Generates random numbers from a uniform distribution over [0, 1). The arguments to np.random.rand are the dimensions of the array you want to create.

In [ ]:
# Generate a 1D array of 5 random numbers from a uniform distribution
random_uniform = np.random.rand(5)
print("Random Uniform 1D Array:", random_uniform)
print()

# Generate a 2D array (3x3) of random numbers
random_uniform_2d = np.random.rand(3, 3)
print("Random Uniform 2D Array:\n", random_uniform_2d)


Random Uniform 1D Array: [0.13396604 0.89579583 0.25100157 0.91714681 0.25503698]

Random Uniform 2D Array:
 [[0.30296987 0.77562706 0.66777927]
 [0.84550587 0.08833776 0.55744979]
 [0.03132606 0.386629   0.76674882]]


2. `np.random.randn`\
Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). The arguments define the dimensions of the output array.

In [ ]:
# Generate a 1D array of 5 random numbers from a standard normal distribution
random_normal = np.random.randn(5)
print("Random Normal 1D Array:", random_normal)
print()

# Generate a 2D array (3x2) of random numbers
random_normal_2d = np.random.randn(3, 2)
print("Random Normal 2D Array:\n", random_normal_2d)


Random Normal 1D Array: [ 0.2376787  -0.32867652 -0.0533874   0.08958133 -0.58988352]

Random Normal 2D Array:
 [[-0.25484062 -0.26367262]
 [-1.05613251 -0.36672365]
 [-1.49936763 -0.02668338]]


  3. `np.random.randint`\
Generates random integers from low (inclusive) to high (exclusive). You can also specify the size of the array

In [ ]:
# Generate 5 random integers from 0 to 10
random_integers = np.random.randint(0, 10, size=5)
print("Random Integers:", random_integers)
print()

# Generate a 2D array (3x3) of random integers from 1 to 100
random_integers_2d = np.random.randint(1, 100, size=(3, 3))
print("Random Integers 2D Array:\n", random_integers_2d)


Random Integers: [8 4 2 7 9]

Random Integers 2D Array:
 [[77 88 28]
 [89 89 22]
 [ 3 86 45]]


4. `np.random.uniform`\
Generates random numbers from a uniform distribution over [low, high](where low is inclusive and high is exclusive). You can specify the size of the output array.

In [ ]:
# Generate 5 random numbers from a uniform distribution between 0 and 1
random_uniform_custom = np.random.uniform(0, 1, 5)
print("Random Uniform Numbers:", random_uniform_custom)
print()

# Generate a 2D array (2x3) of random numbers from 10 to 50
random_uniform_custom_2d = np.random.uniform(10, 50, (2, 3))
print("Random Uniform Numbers 2D Array:\n", random_uniform_custom_2d)


Random Uniform Numbers: [0.27346793 0.03281407 0.66365491 0.91454078 0.75440296]

Random Uniform Numbers 2D Array:
 [[35.15949802 24.74887907 46.27016512]
 [29.55014091 21.42715163 41.12281966]]


- These functions are incredibly useful in simulations, statistical sampling, machine learning randomization, and many other fields where random number generation is necessary. Each function serves different needs depending on the statistical distribution and format required.